### ISSUE TITLE
/taxon_refs requests memory leak?

### ISSUE THREAD

**Issue by gdower** [gnames/bhlnames#19]
Some queries to /taxon_refs run for a really long time and eventually kill the rest server, possibly because the server runs out of memory. For example, try this on sf29:

```
./bhlnames rest -p5128 &
curl -X POST -H "Content-Type: application/json" -d '["Hamotus gracilicornis"]' http://localhost:5128/taxon_refs
```

The only output from the running process was `killed`, but if you run the command and wait for a long time the memory usage keeps increasing.

**Comment by dimus** [comment]
sf29 has some trouble that I do not understand, when I run same queries locally everything is fine

**Comment by dimus** [comment]
I am now getthing the same problem on my home laptop, and it is postgres memory, I suspect I lost an index, trying to figure it out
